# Configuración de golangci-lint para Ferre-POS Servidor Central
# Cumple con estándares Go y considera notación húngara

run:
  # Timeout para análisis
  timeout: 5m
  
  # Directorios a incluir
  modules-download-mode: readonly
  
  # Directorios a excluir
  skip-dirs:
    - vendor
    - docs
    - build
    - bin
    - .git
  
  # Archivos a excluir
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"  # Opcional: excluir tests del linting

# Configuración de output
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

# Configuración de linters
linters:
  enable:
    # Linters básicos recomendados
    - errcheck      # Verifica errores no manejados
    - gosimple      # Simplificaciones de código
    - govet         # Análisis estático estándar
    - ineffassign   # Asignaciones ineficientes
    - staticcheck   # Análisis estático avanzado
    - typecheck     # Verificación de tipos
    - unused        # Variables/funciones no usadas
    
    # Linters de estilo y formato
    - gofmt         # Formato de código
    - goimports     # Imports organizados
    - misspell      # Errores de ortografía
    - whitespace    # Espacios en blanco
    
    # Linters de complejidad
    - gocyclo       # Complejidad ciclomática
    - gocognit      # Complejidad cognitiva
    - funlen        # Longitud de funciones
    - lll           # Longitud de líneas
    
    # Linters de seguridad
    - gosec         # Vulnerabilidades de seguridad
    
    # Linters de performance
    - prealloc      # Pre-asignación de slices
    
    # Linters de buenas prácticas
    - unconvert     # Conversiones innecesarias
    - unparam       # Parámetros no usados
    - goconst       # Constantes repetidas
    - gocritic      # Críticas de código
    - revive        # Reemplazo de golint
    
    # Linters específicos para APIs
    - bodyclose     # Cierre de response bodies
    - noctx         # Uso de context
    
  disable:
    # Deshabilitamos algunos linters que pueden conflictuar con notación húngara
    - varnamelen    # Longitud de nombres de variables (conflicto con notación húngara)
    - stylecheck    # Estilo de nombres (conflicto con notación húngara)
    - golint        # Deprecated, reemplazado por revive

# Configuración específica de linters
linters-settings:
  # Configuración de errcheck
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - fmt.Print
      - fmt.Println
      - fmt.Printf
  
  # Configuración de gocyclo
  gocyclo:
    min-complexity: 15
  
  # Configuración de gocognit
  gocognit:
    min-complexity: 20
  
  # Configuración de funlen
  funlen:
    lines: 100
    statements: 50
  
  # Configuración de lll (line length)
  lll:
    line-length: 120
    tab-width: 4
  
  # Configuración de misspell
  misspell:
    locale: US
    ignore-words:
      - "ferre"
      - "pos"
      - "sucursal"
      - "etiqueta"
      - "reporte"
  
  # Configuración de gosec
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Errores no verificados (manejado por errcheck)
  
  # Configuración de goconst
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
  
  # Configuración de gocritic
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - commentedOutCode
      - ifElseChain
      - singleCaseSwitch
    settings:
      hugeParam:
        sizeThreshold: 80
      rangeValCopy:
        sizeThreshold: 512
  
  # Configuración de revive (reemplazo de golint)
  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        disabled: true  # Deshabilitado para permitir notación húngara
      - name: if-return
      - name: increment-decrement
      - name: var-naming
        disabled: true  # Deshabilitado para permitir notación húngara
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
        disabled: true  # Deshabilitado para permitir notación húngara
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  
  # Configuración de staticcheck
  staticcheck:
    go: "1.21"
    checks: ["all"]
  
  # Configuración de unused
  unused:
    go: "1.21"

# Issues configuration
issues:
  # Excluir algunos archivos de verificación
  exclude-rules:
    # Excluir archivos de test de algunos linters
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    
    # Excluir archivos de configuración
    - path: cmd/
      linters:
        - funlen  # Los main() pueden ser largos
    
    # Excluir archivos de modelos de algunos linters
    - path: internal/models/
      linters:
        - lll  # Los modelos pueden tener líneas largas
        - funlen  # Los métodos de modelos pueden ser largos
    
    # Permitir notación húngara en nombres
    - text: "var-naming"
      linters:
        - revive
    - text: "exported"
      linters:
        - revive
    - text: "receiver-naming"
      linters:
        - revive
  
  # Número máximo de issues a reportar
  max-issues-per-linter: 50
  max-same-issues: 10
  
  # Mostrar solo nuevos issues
  new: false
  
  # Excluir issues por defecto
  exclude-use-default: false
  
  # Patrones de exclusión personalizados
  exclude:
    # Excluir comentarios sobre notación húngara
    - "var-naming: don't use underscores in Go names"
    - "exported .* should have comment or be unexported"
    - "comment on exported .* should be of the form"
    
    # Excluir algunos false positives comunes
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "should have a package comment, unless it's in another file for this package"

# Configuración de severity
severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - revive
      severity: warning
    - linters:
        - gocritic
      severity: info

