# Configuración Específica del API POS
# Este archivo puede ser modificado independientemente del archivo principal
# Los cambios se aplicarán automáticamente sin reiniciar el servidor

# Configuración General del API POS
api:
  enabled: true
  base_path: "/api/pos"
  version: "v1"
  description: "API para operaciones de Punto de Venta"

# Configuración de Rendimiento
performance:
  max_concurrent_users: 100         # Usuarios concurrentes máximos
  session_timeout: "8h"             # Timeout de sesión de usuario
  max_products_per_query: 1000      # Productos máximos por consulta
  cache_products_ttl: "30m"         # TTL del cache de productos
  query_timeout: "30s"              # Timeout para consultas de BD
  max_request_size: "10MB"          # Tamaño máximo de request

# Configuración de Modo Offline
offline:
  allow_offline_mode: true          # Permitir modo offline
  offline_data_retention: "168h"    # Retención de datos offline (7 días)
  sync_on_reconnect: true           # Sincronizar al reconectar
  max_offline_transactions: 1000    # Transacciones offline máximas
  offline_storage_path: "/var/lib/ferre-pos/offline"

# Configuración de Autenticación
authentication:
  require_terminal_auth: true       # Requerir autenticación de terminal
  terminal_session_timeout: "12h"   # Timeout de sesión de terminal
  allow_multiple_sessions: false    # Permitir múltiples sesiones por usuario
  force_password_change: false      # Forzar cambio de contraseña
  password_expiry_days: 90          # Días para expirar contraseña

# Configuración de Ventas
ventas:
  max_venta_items: 100              # Items máximos por venta
  allow_negative_stock: false       # Permitir stock negativo
  require_customer_for_credit: true # Requerir cliente para crédito
  max_discount_percentage: 50       # Descuento máximo permitido
  allow_price_override: false       # Permitir sobrescribir precios
  require_supervisor_approval: true # Requerir aprobación de supervisor
  auto_print_receipt: true          # Imprimir recibo automáticamente

# Configuración de Productos
productos:
  enable_barcode_search: true       # Habilitar búsqueda por código de barras
  cache_product_images: true        # Cachear imágenes de productos
  max_search_results: 50            # Resultados máximos de búsqueda
  enable_product_suggestions: true  # Habilitar sugerencias de productos
  show_stock_levels: true           # Mostrar niveles de stock
  enable_price_alerts: true         # Habilitar alertas de precio

# Configuración de Stock
stock:
  enable_stock_alerts: true         # Habilitar alertas de stock
  low_stock_threshold: 10           # Umbral de stock bajo
  enable_stock_reservations: true   # Habilitar reservas de stock
  reservation_timeout: "30m"        # Timeout de reservas
  auto_release_reservations: true   # Liberar reservas automáticamente

# Configuración de Fidelización
fidelizacion:
  enable_fidelizacion: true         # Habilitar programa de fidelización
  points_per_peso: 1                # Puntos por peso gastado
  min_purchase_for_points: 1000     # Compra mínima para puntos
  points_expiry_months: 12          # Meses para expirar puntos
  enable_birthday_bonus: true       # Bonus de cumpleaños
  birthday_bonus_points: 500        # Puntos de bonus de cumpleaños

# Configuración de Impresión
printing:
  auto_print_receipt: true          # Imprimir recibo automáticamente
  receipt_copies: 1                 # Copias de recibo
  print_customer_copy: true         # Imprimir copia para cliente
  receipt_footer_message: "¡Gracias por su compra!"
  enable_email_receipt: false       # Habilitar recibo por email
  enable_sms_receipt: false         # Habilitar recibo por SMS

# Configuración de Reportes POS
reports:
  enable_daily_reports: true        # Habilitar reportes diarios
  auto_generate_daily_report: true  # Generar reporte diario automáticamente
  daily_report_time: "23:59"        # Hora para generar reporte diario
  enable_shift_reports: true        # Habilitar reportes de turno
  enable_cashier_reports: true      # Habilitar reportes de cajero

# Configuración de Notificaciones
notifications:
  enable_low_stock_alerts: true     # Alertas de stock bajo
  enable_price_change_alerts: true  # Alertas de cambio de precio
  enable_new_product_alerts: false  # Alertas de nuevos productos
  notification_methods:             # Métodos de notificación
    - "email"
    - "system"
  alert_recipients:                 # Destinatarios de alertas
    - "gerente@ferreteria.com"
    - "admin@ferreteria.com"

# Configuración de Integración
integration:
  enable_erp_sync: true             # Habilitar sincronización con ERP
  erp_sync_interval: "15m"          # Intervalo de sincronización
  enable_accounting_sync: true      # Habilitar sincronización contable
  accounting_sync_interval: "1h"    # Intervalo de sincronización contable
  enable_inventory_sync: true       # Habilitar sincronización de inventario

# Configuración de Rate Limiting específica para POS
rate_limiting:
  enabled: true
  requests_per_minute: 200          # Requests por minuto
  burst_size: 20                    # Tamaño de burst
  cleanup_interval: "5m"            # Intervalo de limpieza
  whitelist_ips:                    # IPs exentas de rate limiting
    - "192.168.1.0/24"
    - "10.0.0.0/8"

# Configuración de Cache específica para POS
cache:
  enable_product_cache: true        # Habilitar cache de productos
  product_cache_ttl: "30m"          # TTL del cache de productos
  enable_customer_cache: true       # Habilitar cache de clientes
  customer_cache_ttl: "1h"          # TTL del cache de clientes
  enable_price_cache: true          # Habilitar cache de precios
  price_cache_ttl: "15m"            # TTL del cache de precios

# Configuración de Validaciones
validation:
  validate_customer_data: true      # Validar datos de cliente
  validate_product_data: true       # Validar datos de producto
  strict_barcode_validation: false  # Validación estricta de códigos de barras
  require_valid_email: false        # Requerir email válido
  require_valid_phone: false        # Requerir teléfono válido

# Configuración de Backup
backup:
  enable_transaction_backup: true   # Habilitar backup de transacciones
  backup_interval: "1h"             # Intervalo de backup
  backup_retention_days: 30         # Días de retención de backup
  backup_path: "/var/lib/ferre-pos/backups/pos"
  compress_backups: true            # Comprimir backups

# Configuración de Seguridad específica para POS
security:
  enable_transaction_signing: true  # Habilitar firma de transacciones
  require_pin_for_refunds: true     # Requerir PIN para devoluciones
  require_pin_for_discounts: true   # Requerir PIN para descuentos
  max_cash_amount: 1000000          # Monto máximo en efectivo
  enable_audit_trail: true          # Habilitar rastro de auditoría
  log_all_transactions: true        # Registrar todas las transacciones

# Configuración de UI/UX
ui:
  theme: "default"                  # Tema de la interfaz
  language: "es"                    # Idioma por defecto
  currency: "COP"                   # Moneda por defecto
  date_format: "DD/MM/YYYY"         # Formato de fecha
  time_format: "HH:mm:ss"           # Formato de hora
  enable_keyboard_shortcuts: true   # Habilitar atajos de teclado
  show_product_images: true         # Mostrar imágenes de productos
  enable_touch_interface: true      # Habilitar interfaz táctil

# Configuración de Desarrollo y Debug
development:
  enable_debug_mode: false          # Habilitar modo debug
  log_sql_queries: false            # Registrar consultas SQL
  enable_profiling: false           # Habilitar profiling
  mock_external_services: false     # Simular servicios externos
  enable_test_data: false           # Habilitar datos de prueba

