# Configuración para desarrollo
app:
  environment: "development"

logging:
  level: "debug"
  output: "stdout"
  
connection_pool:
  max_connections: 5

rate_limiting:
  enabled: false

security:
  require_tls: false
  