# Configuración principal del cliente SMTP
app:
  name: "smtp-client"
  version: "1.0.0"
  environment: "development"

# Configuración de logging
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "/var/log/smtp-client.log"
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # días

# Configuración de proveedores
providers:
  gmail:
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    use_tls: true
    timeout: "30s"
    oauth2:
      scopes:
        - "https://www.googleapis.com/auth/gmail.send"
      redirect_url: "http://localhost:8080/callback"
  
  office365:
    smtp_host: "smtp.office365.com"
    smtp_port: 587
    use_tls: true
    timeout: "30s"
    oauth2:
      scopes:
        - "https://outlook.office.com/SMTP.Send"
      redirect_url: "http://localhost:8080/callback"
  
  generic:
    timeout: "30s"

# Configuración del pool de conexiones
connection_pool:
  max_connections: 10
  max_idle_time: "5m"
  connection_timeout: "30s"
  idle_timeout: "10m"
  cleanup_interval: "1m"

# Configuración de seguridad
security:
  token_encryption_key: "" # Se carga desde variable de entorno
  max_token_age: "1h"
  require_tls: true
  allowed_domains: []

# Configuración de rate limiting
rate_limiting:
  enabled: true
  requests_per_minute: 60
  burst: 10

# Configuración de reintentos
retry:
  max_attempts: 3
  initial_backoff: "1s"
  max_backoff: "30s"
  multiplier: 2.0
  
# Configuración de métricas
metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  