# Configuración Específica del API de Reportes
# Este archivo puede ser modificado independientemente del archivo principal
# Los cambios se aplicarán automáticamente sin reiniciar el servidor

# Configuración General del API Reports
api:
  enabled: true
  base_path: "/api/reports"
  version: "v1"
  description: "API para generación de reportes, dashboards y análisis"

# Configuración de Generación de Reportes
generation:
  max_concurrent_reports: 5         # Reportes concurrentes máximos
  max_report_size: 100              # Tamaño máximo por reporte (MB)
  default_format: "pdf"             # Formato por defecto
  supported_formats:                # Formatos soportados
    - "pdf"
    - "excel"
    - "csv"
    - "json"
    - "html"
    - "xml"
  report_timeout: "10m"             # Timeout para generación
  queue_timeout: "1h"               # Timeout en cola
  enable_async_generation: true     # Generación asíncrona

# Configuración de Plantillas de Reportes
templates:
  cache_templates_ttl: "1h"         # TTL del cache de plantillas
  max_template_size: "5MB"          # Tamaño máximo de plantilla
  enable_template_validation: true  # Validar plantillas
  enable_template_versioning: true  # Versionado de plantillas
  max_template_versions: 15         # Versiones máximas por plantilla
  
  # Tipos de plantillas soportadas
  supported_template_types:
    - "sql"                         # Plantillas SQL
    - "json"                        # Plantillas JSON
    - "jinja2"                      # Plantillas Jinja2
    - "mustache"                    # Plantillas Mustache
  
  # Configuración de parámetros
  parameters:
    max_parameters: 50              # Parámetros máximos por plantilla
    enable_parameter_validation: true # Validar parámetros
    allowed_parameter_types:        # Tipos de parámetro permitidos
      - "string"
      - "number"
      - "date"
      - "datetime"
      - "boolean"
      - "array"
      - "object"

# Configuración de Almacenamiento
storage:
  storage_path: "/var/lib/ferre-pos/reports"
  temp_path: "/tmp/ferre-pos/reports"
  max_storage_size: "50GB"          # Tamaño máximo de almacenamiento
  enable_compression: true          # Comprimir reportes almacenados
  compression_level: 6              # Nivel de compresión (1-9)
  enable_encryption: false          # Encriptar reportes almacenados
  
  # Configuración de estructura
  directory_structure:
    by_date: true                   # Organizar por fecha
    by_user: true                   # Organizar por usuario
    by_type: true                   # Organizar por tipo de reporte
    date_format: "2006/01/02"       # Formato de fecha

# Configuración de Limpieza
cleanup:
  cleanup_interval: "24h"           # Intervalo de limpieza
  file_retention_days: 90           # Días para retener reportes
  temp_file_retention_hours: 4      # Horas para archivos temporales
  failed_report_retention_days: 14  # Días para reportes fallidos
  enable_auto_cleanup: true         # Limpieza automática
  cleanup_batch_size: 50            # Tamaño de lote para limpieza

# Configuración de Reportes Programados
scheduled_reports:
  enable_scheduled_reports: true    # Habilitar reportes programados
  max_scheduled_reports: 50         # Reportes programados máximos
  scheduler_interval: "1m"          # Intervalo del scheduler
  max_execution_time: "30m"         # Tiempo máximo de ejecución
  enable_retry_failed: true         # Reintentar reportes fallidos
  max_retry_attempts: 3             # Intentos máximos de reintento
  retry_delay: "5m"                 # Delay entre reintentos
  
  # Configuración de notificaciones
  notifications:
    enable_completion_notifications: true # Notificar completados
    enable_failure_notifications: true    # Notificar fallos
    notification_methods:           # Métodos de notificación
      - "email"
      - "webhook"
    default_recipients:             # Destinatarios por defecto
      - "reportes@ferreteria.com"

# Configuración de Dashboards
dashboards:
  enable_dashboards: true           # Habilitar dashboards
  dashboard_refresh_rate: "5m"      # Tasa de refresco
  max_widgets_per_dashboard: 20     # Widgets máximos por dashboard
  enable_real_time_updates: true    # Actualizaciones en tiempo real
  cache_dashboard_data: true        # Cachear datos de dashboard
  dashboard_cache_ttl: "2m"         # TTL del cache de dashboard
  
  # Tipos de widgets soportados
  supported_widget_types:
    - "chart"                       # Gráficos
    - "table"                       # Tablas
    - "metric"                      # Métricas
    - "gauge"                       # Medidores
    - "map"                         # Mapas
    - "text"                        # Texto
  
  # Configuración de gráficos
  charts:
    default_chart_library: "chartjs" # Librería de gráficos por defecto
    supported_chart_types:          # Tipos de gráfico soportados
      - "line"
      - "bar"
      - "pie"
      - "doughnut"
      - "area"
      - "scatter"
      - "bubble"
    max_data_points: 10000          # Puntos de datos máximos por gráfico

# Configuración de Cache
cache:
  enable_report_cache: true         # Habilitar cache de reportes
  report_cache_ttl: "1h"            # TTL del cache de reportes
  enable_query_cache: true          # Habilitar cache de consultas
  query_cache_ttl: "30m"            # TTL del cache de consultas
  enable_data_cache: true           # Habilitar cache de datos
  data_cache_ttl: "15m"             # TTL del cache de datos
  max_cache_size: "1GB"             # Tamaño máximo de cache
  cache_cleanup_interval: "1h"      # Intervalo de limpieza de cache

# Configuración de Base de Datos
database:
  enable_query_optimization: true   # Optimización de consultas
  max_query_execution_time: "5m"    # Tiempo máximo de ejecución de consulta
  enable_query_logging: true        # Logging de consultas
  log_slow_queries: true            # Registrar consultas lentas
  slow_query_threshold: "10s"       # Umbral para consultas lentas
  max_result_rows: 100000           # Filas máximas en resultado
  
  # Configuración de conexiones
  connections:
    max_connections: 10             # Conexiones máximas
    connection_timeout: "30s"       # Timeout de conexión
    idle_timeout: "5m"              # Timeout de inactividad
    max_lifetime: "1h"              # Tiempo de vida máximo de conexión

# Configuración de Seguridad
security:
  enable_sql_injection_protection: true # Protección contra SQL injection
  allowed_sql_keywords:             # Keywords SQL permitidos
    - "SELECT"
    - "FROM"
    - "WHERE"
    - "GROUP BY"
    - "ORDER BY"
    - "HAVING"
    - "JOIN"
    - "UNION"
  blocked_sql_keywords:             # Keywords SQL bloqueados
    - "DROP"
    - "DELETE"
    - "UPDATE"
    - "INSERT"
    - "CREATE"
    - "ALTER"
    - "TRUNCATE"
  enable_data_masking: true         # Enmascaramiento de datos sensibles
  sensitive_fields:                 # Campos sensibles a enmascarar
    - "password"
    - "email"
    - "phone"
    - "ssn"
    - "credit_card"

# Configuración de Performance
performance:
  enable_parallel_processing: true  # Procesamiento paralelo
  max_worker_threads: 6             # Threads de worker máximos
  worker_queue_size: 500            # Tamaño de cola de workers
  enable_memory_optimization: true  # Optimización de memoria
  max_memory_usage: "2GB"           # Uso máximo de memoria
  enable_streaming: true            # Streaming para reportes grandes
  streaming_chunk_size: "1MB"       # Tamaño de chunk para streaming
  
  # Configuración de límites
  limits:
    max_concurrent_queries: 10      # Consultas concurrentes máximas
    max_report_pages: 1000          # Páginas máximas por reporte
    max_chart_data_points: 50000    # Puntos de datos máximos en gráficos

# Configuración de Exportación
export:
  enable_bulk_export: true          # Habilitar exportación masiva
  max_export_size: "500MB"          # Tamaño máximo de exportación
  export_timeout: "30m"             # Timeout de exportación
  supported_export_formats:         # Formatos de exportación
    - "pdf"
    - "excel"
    - "csv"
    - "json"
    - "xml"
    - "zip"
  
  # Configuración por formato
  pdf:
    default_page_size: "A4"
    default_orientation: "portrait"
    enable_bookmarks: true
    enable_compression: true
  
  excel:
    max_rows_per_sheet: 1000000
    enable_formulas: false
    enable_charts: true
    default_format: "xlsx"
  
  csv:
    default_delimiter: ","
    default_encoding: "UTF-8"
    include_headers: true
    quote_all_fields: false

# Configuración de Logging
logging:
  log_report_generation: true       # Registrar generación de reportes
  log_query_execution: true         # Registrar ejecución de consultas
  log_dashboard_access: true        # Registrar acceso a dashboards
  log_performance_metrics: true     # Registrar métricas de rendimiento
  log_user_actions: true            # Registrar acciones de usuario
  
  # Configuración detallada
  detailed_logging:
    log_sql_queries: false          # Registrar consultas SQL
    log_query_parameters: false     # Registrar parámetros de consulta
    log_execution_plans: false      # Registrar planes de ejecución
    log_memory_usage: true          # Registrar uso de memoria

# Configuración de Notificaciones
notifications:
  enable_report_notifications: true # Notificar reportes completados
  enable_error_notifications: true  # Notificar errores
  enable_performance_alerts: true   # Alertas de rendimiento
  enable_quota_notifications: true  # Notificar límites de cuota
  
  # Destinatarios
  recipients:
    admin: "reports-admin@ferreteria.com"
    users: "usuarios@ferreteria.com"
    managers: "gerentes@ferreteria.com"
  
  # Configuración de alertas
  alerts:
    report_failure_threshold: 3     # Fallos consecutivos para alerta
    query_timeout_threshold: 5      # Timeouts para alerta
    storage_usage_threshold: 85     # % de uso de almacenamiento
    memory_usage_threshold: 80      # % de uso de memoria

# Configuración de Integración
integration:
  enable_data_sources: true         # Habilitar fuentes de datos externas
  max_data_sources: 10              # Fuentes de datos máximas
  connection_pool_size: 5           # Tamaño de pool de conexiones
  
  # Fuentes de datos soportadas
  supported_data_sources:
    - "postgresql"
    - "mysql"
    - "sqlite"
    - "mongodb"
    - "elasticsearch"
    - "api"
    - "csv"
    - "json"
  
  # APIs externas
  external_apis:
    pos_api:
      enabled: true
      endpoint: "http://localhost:8080/api/pos"
      timeout: "30s"
      retry_attempts: 3
    
    sync_api:
      enabled: true
      endpoint: "http://localhost:8080/api/sync"
      timeout: "60s"
      retry_attempts: 2

# Configuración de Cuotas
quotas:
  enable_user_quotas: true          # Habilitar cuotas por usuario
  default_user_quota: 100           # Reportes por usuario por día
  enable_storage_quotas: true       # Habilitar cuotas de almacenamiento
  default_storage_quota: "5GB"      # Almacenamiento por usuario
  enable_execution_quotas: true     # Habilitar cuotas de ejecución
  default_execution_quota: "1h"     # Tiempo de ejecución por usuario por día
  
  # Límites por rol
  role_limits:
    admin:
      daily_reports: 1000
      storage_quota: "50GB"
      execution_quota: "10h"
    
    manager:
      daily_reports: 500
      storage_quota: "20GB"
      execution_quota: "5h"
    
    user:
      daily_reports: 100
      storage_quota: "5GB"
      execution_quota: "1h"

# Configuración de Backup
backup:
  enable_report_backup: true        # Backup de reportes
  enable_template_backup: true      # Backup de plantillas
  backup_interval: "6h"             # Intervalo de backup
  backup_retention_days: 180        # Días de retención
  backup_path: "/var/lib/ferre-pos/backups/reports"
  compress_backups: true            # Comprimir backups
  include_generated_reports: false  # Incluir reportes generados
  
  # Configuración de restauración
  restore:
    enable_auto_restore: false      # Restauración automática
    restore_timeout: "30m"          # Timeout de restauración

# Configuración de Desarrollo
development:
  enable_debug_mode: false          # Habilitar modo debug
  enable_query_debugging: false     # Debug de consultas
  save_intermediate_results: false  # Guardar resultados intermedios
  enable_performance_profiling: false # Profiling de rendimiento
  mock_external_services: false     # Simular servicios externos
  
  # Configuración de testing
  testing:
    enable_test_data: false         # Habilitar datos de prueba
    test_data_path: "/var/lib/ferre-pos/test-data/reports"
    enable_load_testing: false      # Habilitar pruebas de carga
    max_test_reports: 1000          # Reportes máximos para testing

# Configuración de Monitoreo
monitoring:
  enable_metrics: true              # Habilitar métricas
  metrics_interval: "30s"           # Intervalo de métricas
  enable_health_checks: true        # Habilitar health checks
  health_check_interval: "1m"       # Intervalo de health checks
  
  # Métricas específicas
  metrics:
    report_generation_time: true    # Tiempo de generación
    query_execution_time: true      # Tiempo de ejecución de consultas
    cache_hit_rate: true            # Tasa de acierto de cache
    memory_usage: true              # Uso de memoria
    storage_usage: true             # Uso de almacenamiento
    active_users: true              # Usuarios activos
    concurrent_reports: true        # Reportes concurrentes

