# Configuración Principal - Sistema FERRE-POS
# Archivo modificable para configurar los 4 módulos API REST

# Configuración de Base de Datos
database:
  host: "localhost"
  port: 5432
  name: "ferre_pos_central"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"
  max_open_connections: 100
  max_idle_connections: 10
  connection_max_lifetime: "1h"
  connection_max_idle_time: "30m"

# Configuración de Logging
logging:
  level: "info"  # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, file
  file_path: "/var/log/ferre_pos/"
  max_size_mb: 100
  max_backups: 5
  max_age_days: 30
  compress: true

# Configuración de Métricas Prometheus
metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  namespace: "ferre_pos"
  subsystem: ""
  collect_runtime_metrics: true
  collect_database_metrics: true

# Configuración de Rate Limiting
rate_limiting:
  enabled: true
  requests_per_second: 100
  burst_size: 200
  cleanup_interval: "1m"
  
# Configuración específica por API
apis:
  # API POS - Máxima prioridad
  pos:
    enabled: true
    port: 8080
    host: "0.0.0.0"
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
    max_header_bytes: 1048576
    rate_limiting:
      requests_per_second: 200
      burst_size: 400
    cache:
      enabled: true
      ttl: "5m"
      max_entries: 10000
    auth:
      jwt_secret: "pos_secret_key_change_in_production"
      token_expiry: "8h"
      refresh_token_expiry: "24h"
    
  # API Sync - Prioridad media
  sync:
    enabled: true
    port: 8081
    host: "0.0.0.0"
    read_timeout: "60s"
    write_timeout: "60s"
    idle_timeout: "120s"
    max_header_bytes: 2097152
    rate_limiting:
      requests_per_second: 50
      burst_size: 100
    batch_processing:
      max_batch_size: 1000
      timeout: "5m"
    retry:
      max_attempts: 3
      initial_delay: "1s"
      max_delay: "30s"
    auth:
      jwt_secret: "sync_secret_key_change_in_production"
      token_expiry: "24h"
      refresh_token_expiry: "72h"
      
  # API Labels - Prioridad baja
  labels:
    enabled: true
    port: 8082
    host: "0.0.0.0"
    read_timeout: "45s"
    write_timeout: "45s"
    idle_timeout: "90s"
    max_header_bytes: 1048576
    rate_limiting:
      requests_per_second: 30
      burst_size: 60
    label_generation:
      max_concurrent_jobs: 10
      job_timeout: "10m"
      temp_directory: "/tmp/ferre_pos_labels"
      output_formats: ["pdf", "png", "zpl"]
    cache:
      enabled: true
      ttl: "30m"
      max_entries: 5000
    auth:
      jwt_secret: "labels_secret_key_change_in_production"
      token_expiry: "12h"
      refresh_token_expiry: "48h"
      
  # API Reports - Prioridad mínima
  reports:
    enabled: true
    port: 8083
    host: "0.0.0.0"
    read_timeout: "120s"
    write_timeout: "120s"
    idle_timeout: "300s"
    max_header_bytes: 2097152
    rate_limiting:
      requests_per_second: 10
      burst_size: 20
    report_generation:
      max_concurrent_reports: 5
      report_timeout: "30m"
      temp_directory: "/tmp/ferre_pos_reports"
      output_formats: ["pdf", "excel", "csv"]
      max_rows_per_report: 100000
    cache:
      enabled: true
      ttl: "1h"
      max_entries: 1000
    auth:
      jwt_secret: "reports_secret_key_change_in_production"
      token_expiry: "24h"
      refresh_token_expiry: "72h"

# Configuración de Seguridad
security:
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    exposed_headers: ["X-Total-Count", "X-Request-ID"]
    allow_credentials: true
    max_age: 86400
  
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation_interval: "24h"
    
  session:
    secure: false  # true en producción
    http_only: true
    same_site: "lax"
    max_age: 86400

# Configuración de Monitoreo
monitoring:
  health_check:
    enabled: true
    path: "/health"
    interval: "30s"
    timeout: "10s"
  
  profiling:
    enabled: false  # true solo en desarrollo
    path: "/debug/pprof"
    
  tracing:
    enabled: false
    jaeger_endpoint: "http://localhost:14268/api/traces"
    service_name: "ferre-pos-api"

# Configuración de Desarrollo
development:
  debug: false
  hot_reload: false
  mock_external_services: false
  test_data_enabled: false

